CREATE DATABASE QLNOITHAT
GO

--KHÁCH HÀNG
CREATE TABLE KHACHHANG(
MAKH VARCHAR(15),
TENKH NVARCHAR(50),
SDT VARCHAR(50),
DIACHI NVARCHAR(50),
TRANGTHAI BIT
CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH))
--CHẤT LIỆU SẢN  PHẨM
CREATE TABLE CHATLIEUSP(
MACLSP VARCHAR(15),
CHATLIEU NVARCHAR(20),
CONSTRAINT PK_CHATLIEUSP PRIMARY KEY (MACLSP))
--SẢN PHẨM 
CREATE TABLE SANPHAM(
MASP VARCHAR(15),
TENSP NVARCHAR(50)
CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP)
)
--THƯƠNG HIỆU 
CREATE TABLE THUONGHIEU(
MATH VARCHAR(15),
THUONGHIEU NVARCHAR(50),
CONSTRAINT PK_THUONGHIEU PRIMARY KEY (MATH)
)
-- CHI TIẾT SẢN PHẨM
CREATE TABLE CTSANPHAM(
MACTSP VARCHAR(15),
MASP VARCHAR(15),
TENSP NVARCHAR(100),
SOLUONG INT,
DONGIA MONEY,
ANSP NVARCHAR(50),
MOTA NVARCHAR(100),
MATH VARCHAR(15),
MACLSP VARCHAR(15)
CONSTRAINT PK_CTSANPHAM PRIMARY KEY (MACTSP),
CONSTRAINT FK_SANPHAM_CTSANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM,
CONSTRAINT FK_THUONGHIEU_CTSANPHAM FOREIGN KEY (MATH) REFERENCES THUONGHIEU,
CONSTRAINT FK_CHATLIEUSP_CTSANPHAM FOREIGN KEY (MACLSP)REFERENCES CHATLIEUSP
)
--TÀI KHOẢN
CREATE TABLE TAIKHOAN(
TENTK VARCHAR(15),
MATKHAU NVARCHAR(20),
HOTEN NVARCHAR(50),
VAITRO BIT,
TRANGTHAI BIT,
PRIMARY KEY (TENTK))
--SỰ KIỆN
CREATE TABLE SUKIEN(
MASK VARCHAR(15),
TENSK NVARCHAR(50),
UUDAI FLOAT,
TGBATDAU DATE,
TGKETTHIC DATE,
TRANGTHAI BIT
PRIMARY KEY (MASK)
)
--HÓA ĐƠN
CREATE TABLE HOADON (
MAHD VARCHAR(15),
MACTSP VARCHAR(15),
MAKH VARCHAR(15),
TENTK VARCHAR(15),
MASK VARCHAR(15),
UUDAI FLOAT,
TONGTIENTT MONEY,
TRANGTHAI BIT
PRIMARY KEY (MAHD),
foreign key(MACTSP) references CTSANPHAM,
foreign key(MAKH) references KHACHHANG,
foreign key(TENTK) references TAIKHOAN,
foreign key(MASK) references SUKIEN)
--CT HÓA ĐƠN 
CREATE TABLE CTHOADON(
MAHD VARCHAR(15),
MACTSP VARCHAR(15),
TENSP NVARCHAR(50),
SOLUONG INT,
DONGIA MONEY,
THANHTIEN MONEY,
TRANGTHAI BIT
foreign key(MAHD) references HOADON,
FOREIGN KEY (MACTSP) REFERENCES CTSANPHAM)






